### ISSUE TITLE
PHP 7.2: count(): Parameter must be an array or an object that implements Countable

### ISSUE THREAD

**Issue by acip** [bugsnag/bugsnag-php#557] opened 2019-12-22 08:54 UTC
### Description
*count(): Parameter must be an array or an object that implements Countable* warning is raised.

### Issue
```php
        $sessions = $this->getSessionCounts();
        $this->setSessionCounts([]);
        if (count($sessions) == 0) {
            return;
        }
```
in bugsnag/bugsnag/src/SessionTracker.php:285
### Environment

* bugsnag-php version: 3.19.0
* PHP version: 7.2

**Comment by GrahamCampbell** [comment] 2019-12-22 09:13
Thanks for the report. Are you using Bugsnag with the Laravel or Symfony library, or natively? This error can only be caused by the function given to `setStorageFunction`, returning `null`.

**Comment by acip** [comment] 2019-12-22 09:33
Laravel

**Comment by johnkiely1** [comment] 2020-04-29 15:41
This has been fixed in version [v3.21.0](https://github.com/bugsnag/bugsnag-php/releases/tag/v3.21.0)

**Closed by johnkiely1** 2020-04-29 15:41 UTC
Labels: bug, scheduled
